[book]
authors = ["connerohnesorge"]
language = "en"
multilingual = false
src = "src"
title = "wrtype Documentation"
description = "A Rust implementation of wtype - xdotool type for Wayland"

[preprocessor.open-on-gh]
command = "mdbook-open-on-gh"
renderer = ["html"]

[preprocessor.cmdrun]
command = "mdbook-cmdrun"
renderer = ["html"]

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
copy-fonts = true
no-section-label = false
git-repository-url = "https://github.com/conneroisu/wrtype"
edit-url-template = "https://github.com/conneroisu/wrtype/edit/main/docs/{path}"

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3

[output.html.print]
enable = true